-- Adminer 4.8.1 PostgreSQL 14.1 dump

\connect "coviddb";

DROP TABLE IF EXISTS "account";
CREATE TABLE "public"."account" (
    "id" bigint DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "balance" bigint,
    "blocked" boolean,
    "password" character varying(255),
    "role" character varying(255),
    "username" character varying(255),
    "patient_id" bigint,
    CONSTRAINT "account_pkey" PRIMARY KEY ("id")
) WITH (oids = false);


DROP TABLE IF EXISTS "account_histories";
CREATE TABLE "public"."account_histories" (
    "id" bigint DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "action" character varying(255),
    "created_date" timestamp(6),
    "account_id" bigint,
    CONSTRAINT "account_histories_pkey" PRIMARY KEY ("id")
) WITH (oids = false);


DROP TABLE IF EXISTS "category";
CREATE TABLE "public"."category" (
    "id" bigint DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "limit_person" integer NOT NULL,
    "limit_time" character varying(255),
    "name" character varying(255),
    CONSTRAINT "category_pkey" PRIMARY KEY ("id")
) WITH (oids = false);


DROP TABLE IF EXISTS "district";
CREATE TABLE "public"."district" (
    "id" bigint DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" character varying(255),
    "province_id" bigint,
    CONSTRAINT "district_pkey" PRIMARY KEY ("id")
) WITH (oids = false);


DROP TABLE IF EXISTS "hospital";
CREATE TABLE "public"."hospital" (
    "id" bigint DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "address" character varying(255),
    "current_size" integer NOT NULL,
    "name" character varying(255),
    "size" integer NOT NULL,
    "district_id" bigint,
    "province_id" bigint,
    "ward_id" bigint,
    CONSTRAINT "hospital_pkey" PRIMARY KEY ("id")
) WITH (oids = false);


DROP TABLE IF EXISTS "hospital_histories";
CREATE TABLE "public"."hospital_histories" (
    "id" bigint DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "export_time" timestamp(6),
    "hospital_name" character varying(255),
    "import_time" timestamp(6),
    "patient_id" bigint,
    CONSTRAINT "hospital_histories_pkey" PRIMARY KEY ("id")
) WITH (oids = false);


DROP TABLE IF EXISTS "image";
CREATE TABLE "public"."image" (
    "id" bigint DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "path" character varying(255),
    "product_id" bigint,
    CONSTRAINT "image_pkey" PRIMARY KEY ("id")
) WITH (oids = false);


DROP TABLE IF EXISTS "order_product";
CREATE TABLE "public"."order_product" (
    "id" bigint DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "quantity" integer NOT NULL,
    "order_id" bigint,
    "product_id" bigint,
    CONSTRAINT "order_product_pkey" PRIMARY KEY ("id")
) WITH (oids = false);


DROP TABLE IF EXISTS "orders";
CREATE TABLE "public"."orders" (
    "id" bigint DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_time" timestamp(6),
    "total_amount" real NOT NULL,
    "total_product" integer NOT NULL,
    "category_id" bigint,
    "patient_id" bigint,
    CONSTRAINT "orders_pkey" PRIMARY KEY ("id")
) WITH (oids = false);


DROP TABLE IF EXISTS "patient";
CREATE TABLE "public"."patient" (
    "id" bigint DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "credit" bigint NOT NULL,
    "debt" bigint NOT NULL,
    "identity" character varying(255),
    "name" character varying(255),
    "payment_min" bigint NOT NULL,
    "status" character varying(255),
    "district_id" bigint,
    "hospital_id" bigint,
    "parent_id" bigint,
    "province_id" bigint,
    "ward_id" bigint,
    "dob" timestamp(6) NOT NULL,
    CONSTRAINT "patient_pkey" PRIMARY KEY ("id")
) WITH (oids = false);


DROP TABLE IF EXISTS "product";
CREATE TABLE "public"."product" (
    "id" bigint DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "amount" real,
    "name" character varying(255),
    "unit" character varying(255),
    CONSTRAINT "product_pkey" PRIMARY KEY ("id")
) WITH (oids = false);


DROP TABLE IF EXISTS "product_categories";
CREATE TABLE "public"."product_categories" (
    "id" bigint DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "limit_product" integer NOT NULL,
    "category_id" bigint,
    "product_id" bigint,
    CONSTRAINT "product_category_pkey" PRIMARY KEY ("id")
) WITH (oids = false);


DROP TABLE IF EXISTS "province";
CREATE TABLE "public"."province" (
    "id" bigint DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" character varying(255),
    CONSTRAINT "province_pkey" PRIMARY KEY ("id")
) WITH (oids = false);


DROP TABLE IF EXISTS "status_histories";
CREATE TABLE "public"."status_histories" (
    "id" bigint DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "destination" character varying(255),
    "source" character varying(255),
    "patient_id" bigint,
    "created_date" timestamp(6) NOT NULL,
    CONSTRAINT "status_histories_pkey" PRIMARY KEY ("id")
) WITH (oids = false);


DROP TABLE IF EXISTS "transaction_histories";
CREATE TABLE "public"."transaction_histories" (
    "id" bigint DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "amount" double precision NOT NULL,
    "created_date" timestamp(6),
    "description" character varying(255),
    "method" character varying(255),
    "status" character varying(255),
    "patient_id" bigint,
    CONSTRAINT "transaction_histories_pkey" PRIMARY KEY ("id")
) WITH (oids = false);


DROP TABLE IF EXISTS "ward";
CREATE TABLE "public"."ward" (
    "id" bigint DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" character varying(255),
    "district_id" bigint,
    CONSTRAINT "ward_pkey" PRIMARY KEY ("id")
) WITH (oids = false);


ALTER TABLE ONLY "public"."account" ADD CONSTRAINT "fkqeqbft17ojmddumyd99fkyehg" FOREIGN KEY (patient_id) REFERENCES patient(id) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."account_histories" ADD CONSTRAINT "fkbjcn111gt8i12uu5owwcf11yh" FOREIGN KEY (account_id) REFERENCES account(id) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."district" ADD CONSTRAINT "fk276utu38g5lgqeth6pwfm3rw2" FOREIGN KEY (province_id) REFERENCES province(id) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."hospital" ADD CONSTRAINT "fkm6ixsb5opmtkq4oy788d0eqku" FOREIGN KEY (ward_id) REFERENCES ward(id) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."hospital" ADD CONSTRAINT "fkqh0w6y6qr5q1h8eia74uuxc1y" FOREIGN KEY (province_id) REFERENCES province(id) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."hospital" ADD CONSTRAINT "fktgak2rgvr12h50jmemj4ec3eb" FOREIGN KEY (district_id) REFERENCES district(id) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."hospital_histories" ADD CONSTRAINT "fkj5uwog9fs87jpx6yu6x6h09c2" FOREIGN KEY (patient_id) REFERENCES patient(id) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."image" ADD CONSTRAINT "fkgpextbyee3uk9u6o2381m7ft1" FOREIGN KEY (product_id) REFERENCES product(id) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."order_product" ADD CONSTRAINT "fkhnfgqyjx3i80qoymrssls3kno" FOREIGN KEY (product_id) REFERENCES product(id) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."order_product" ADD CONSTRAINT "fkl5mnj9n0di7k1v90yxnthkc73" FOREIGN KEY (order_id) REFERENCES orders(id) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."orders" ADD CONSTRAINT "fk6161shkjqug4b2dsdu5g3emyl" FOREIGN KEY (category_id) REFERENCES category(id) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."orders" ADD CONSTRAINT "fkgrc0y8p5nsfxonpp4xolxxglc" FOREIGN KEY (patient_id) REFERENCES patient(id) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."patient" ADD CONSTRAINT "fk5u7hgucxoppt13cnq6d1jku73" FOREIGN KEY (parent_id) REFERENCES patient(id) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."patient" ADD CONSTRAINT "fk8ena1rkb5kdlhqalyfxif5hk1" FOREIGN KEY (province_id) REFERENCES province(id) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."patient" ADD CONSTRAINT "fkfrtkp1fawf55kilsxb1uxpio0" FOREIGN KEY (hospital_id) REFERENCES hospital(id) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."patient" ADD CONSTRAINT "fkj8tcgt32iya29rfi0fkju88yf" FOREIGN KEY (district_id) REFERENCES district(id) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."patient" ADD CONSTRAINT "fkl1wwwexsf24hcuxbxy3og8gqn" FOREIGN KEY (ward_id) REFERENCES ward(id) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."product_categories" ADD CONSTRAINT "fk2k3smhbruedlcrvu6clued06x" FOREIGN KEY (product_id) REFERENCES product(id) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."product_categories" ADD CONSTRAINT "fkkud35ls1d40wpjb5htpp14q4e" FOREIGN KEY (category_id) REFERENCES category(id) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."status_histories" ADD CONSTRAINT "fkek3mho1vf61shs6tvkq7mnvid" FOREIGN KEY (patient_id) REFERENCES patient(id) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."transaction_histories" ADD CONSTRAINT "fk159xvvg1igw4djabuq50k5if6" FOREIGN KEY (patient_id) REFERENCES patient(id) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."ward" ADD CONSTRAINT "fkslko72wj5nauqvsgefqkvwpsb" FOREIGN KEY (district_id) REFERENCES district(id) NOT DEFERRABLE;

-- 2022-01-16 07:58:51.654962+00
